### ISSUE TITLE
list-all method seems to have unexpected output

### ISSUE THREAD

**Issue by NgManSing** [AY2021S2-CS2113-W10-3/tp#27]
![image](https://user-images.githubusercontent.com/77456180/110507383-ed0bec80-813a-11eb-8fac-4db356506573.png)

A: The expected number should be 2 but the actual output is 1

B: I think if the user does not provide description, not displaying is better since the user may be unable to know if "No description available" is added by him or system generated.

**Comment by jovanhuang** [comment]
Thanks Sam for checking. My bad, I will make the changes asap.
